#port
server:
  port: 8763
spring:
  #spring-app-name
  application:
    name: spring-cloud-consumer
  #kafka
  kafka:
    bootstrap-servers: 192.168.1.233:9092
    producer:
      retries: 0
      batch-size: 1024
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 3
    template:
      default-topic: hello
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#eureka-uri
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/
#feign
feign:
  #set-hystrix-enabled
  hystrix:
    enabled: true
  #feign-client-timeout
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  #set-request-body-get
  httpclient:
    enabled: true
#hystrix-timeout
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#ribbon-type
spring-cloud-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule