#port
server:
  port: 8763
#spring
spring:
  application:
    name: spring-cloud-consumer
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#eureka
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/
#hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#ribbon
spring-cloud-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule