#spring
spring:
  application:
    name: spring-cloud-zuul
#port
server:
  port: 8762
#eureka
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/
#zuul
zuul:
  routes:
    api-a:
      path: /consumer/**
      service-id: spring-cloud-consumer
#zuul\u8D85\u65F6
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000