#port
server:
  port: 8765
#app-name
spring:
  application:
    name: spring-cloud-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example?useSSL=false
    username: root
    password: root
#eureka
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/

